# Generated by Django 4.1.7 on 2023-02-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tlg', models.URLField(blank=True, verbose_name='Ссылка на соц. сети')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('stack', models.TextField(blank=True, verbose_name='Навыки')),
                ('hobbies', models.TextField(blank=True, verbose_name='Хобби')),
                ('post', models.CharField(choices=[(None, 'Выберете вашу должность'), ('Нач. отд.', 'Начальник отдела'), ('HR', 'Сотрудник отдела кадров'), ('NE', 'Новый сотрудник')], max_length=30, verbose_name='Должность')),
                ('achievement', models.CharField(blank=True, max_length=200, verbose_name='Достижения')),
                ('rank', models.IntegerField(blank=True, default=100, verbose_name='Ранг')),
                ('point', models.IntegerField(blank=True, default=0, verbose_name='Очки')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новый сотрудник',
                'verbose_name_plural': 'Новые сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tlg', models.URLField(blank=True, verbose_name='Ссылка на соц. сети')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('stack', models.TextField(blank=True, verbose_name='Навыки')),
                ('hobbies', models.TextField(blank=True, verbose_name='Хобби')),
                ('post', models.CharField(choices=[(None, 'Выберете вашу должность'), ('Нач. отд.', 'Начальник отдела'), ('HR', 'Сотрудник отдела кадров'), ('NE', 'Новый сотрудник')], max_length=30, verbose_name='Должность')),
                ('employees', models.ManyToManyField(to='new_employees.newemployee')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работник HR службы',
                'verbose_name_plural': 'Работники HR службы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tlg', models.URLField(blank=True, verbose_name='Ссылка на соц. сети')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('stack', models.TextField(blank=True, verbose_name='Навыки')),
                ('hobbies', models.TextField(blank=True, verbose_name='Хобби')),
                ('post', models.CharField(choices=[(None, 'Выберете вашу должность'), ('Нач. отд.', 'Начальник отдела'), ('HR', 'Сотрудник отдела кадров'), ('NE', 'Новый сотрудник')], max_length=30, verbose_name='Должность')),
                ('subordinates', models.ManyToManyField(to='new_employees.newemployee')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Начальник отдела',
                'verbose_name_plural': 'Начальники отдела',
                'ordering': ['full_name'],
            },
        ),
    ]
