# Generated by Django 4.1.7 on 2023-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
    ]
