# Generated by Django 4.1.7 on 2023-02-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0002_alter_boss_birthday_alter_hr_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Задание')),
                ('deadline', models.DateField(verbose_name='Крайний срок сдачи')),
                ('completed', models.BooleanField(default=False, verbose_name='Сдано/не сдано')),
            ],
        ),
        migrations.AddField(
            model_name='newemployee',
            name='missions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='new_employees.missionsmodel', verbose_name='Задания'),
        ),
    ]
