# Generated by Django 4.1.7 on 2023-03-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0003_missionsmodel_newemployee_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='missions',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='new_employees.missionsmodel', verbose_name='Задания'),
        ),
    ]
