# Generated by Django 4.1.7 on 2023-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0004_alter_newemployee_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionsmodel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='missionsmodel',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Крайний срок сдачи'),
        ),
        migrations.AlterField(
            model_name='missionsmodel',
            name='points',
            field=models.IntegerField(blank=True, verbose_name='Количество очков за задание'),
        ),
    ]
