# Generated by Django 4.1.7 on 2023-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0005_alter_missionsmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionsmodel',
            name='points',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество очков за задание'),
        ),
    ]
