# Generated by Django 4.1.7 on 2023-03-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0006_alter_missionsmodel_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newemployee',
            name='missions',
        ),
        migrations.AddField(
            model_name='missionsmodel',
            name='employee',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='new_employees.newemployee', verbose_name='Задания'),
        ),
    ]
