# Generated by Django 4.1.7 on 2023-03-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_employees', '0007_remove_newemployee_missions_missionsmodel_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionsmodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_employees.newemployee', verbose_name='Задания'),
        ),
    ]
